pretrain:
  batch_size: 300
  random_seed: 1
  generate_num: 30000
  max_length: 140
  model_path: 'results/chembl_pretrain/'
  save_path: 'results/chembl_pretrain/generation/pretrain'

policy:
  vocab_path: 'results/chembl_pretrain/'
  model_path: 'outputs/2022-06-21/16-31-50/results/chembl_finetune/'
  save_path: 'results/chembl_pretrain/generation/drd2/'
  batch_size: 100
  random_seed: 1
  generate_num: 5000
  max_length: 140

irl:
  vocab_path: 'results/chembl_pretrain/'
  model_path: 'outputs/2022-07-05/20-54-52/results/chembl_finetune/'
  save_path: 'results/chembl_pretrain/generation/drd2_htr1a/2022-07-05/20-54-52/'
  batch_size: 30
  random_seed: 1
  generate_num: 30000
  max_length: 140

gail:
  vocab_path: 'results/chembl_pretrain/'
  model_path: 'outputs/2022-09-16/09-10-02/results/chembl_finetune/'
  save_path: 'results/chembl_pretrain/generation/drd2_htr1a/2022-09-16/09-10-02(decision_sf_results)/'
  batch_size: 300
  random_seed: 1
  generate_num: 30000
  max_length: 140
